let Game = require('../../src/models/game.js');
let TileBox = require('../../src/models/tileBox.js');
const Player = require('../../src/models/player.js');
const mockRandomTiles = require('./mockRandomTiles.js').getTiles;

let tileBox = new TileBox(12,9,mockRandomTiles);
let game = new Game(3,tileBox);
let player1 = new Player(0, 'aditi');
let player2 = new Player(1, 'harshad');
let player3 = new Player(2, 'sachin');
game.addPlayer(player1);
game.addPlayer(player2);
game.addPlayer(player3);
game.start();
game.placeTile(0,'4A');
game.startHotel('Sackson',0);
game.purchaseShares('Sackson',3,0);
game.placeTile(1,'10A');
game.purchaseShares('Sackson',3,1);
game.placeTile(2,'4B');
game.purchaseShares('Sackson',3,2);
game.placeTile(0,'5A');
game.purchaseShares('Sackson',3,0);
game.placeTile(1,'12A');
// game.startHotel('Zeta',1);
game.purchaseShares('Sackson',3,1);
game.placeTile(2,'5B');
game.purchaseShares('Sackson',3,2);
game.placeTile(0,'6A');
game.purchaseShares('Sackson',3,0);
game.placeTile(1,'1B');
game.purchaseShares('Sackson',3,1);

module.exports=game;
